
* Tema principal
** TODO Evaluar la presencia de lo conversado con alejo

Se relacionan valores recogidos por el sitio Next Big Sound con apariciones en el territorio.
* Contraparte
** TODO Encontrar ejemplos de la contraparte

** TODO Poner el caso de Rey Gordiflon
* Estilo
** TODO evaluar imagenes poéticas

Reflexiones:
- para un proyecto musical puede ser frustrante sentirse muy popular en las redes sociales pero no tener asistencia a sus conciertos.
- Se relacionan valores recogidos por el sitio Next Big Sound con apariciones en el territorio.
- La industria de la música esta intermediada por las redes sociales haciendo parecer esencial ser popular en ellas para lograr una masa critica de seguidores que permita la sostenibilidad financiera del proyecto.
- La época empuja a los proyectos a contribuir a la asiendad del click, concursos de popularidad, súplicas por likes etc.
- Llama la atención el fenómeno positivista amplificado por Facebook donde solo esta la  opción de expresión liviana de aprobación (ícono de "me gusta"), muy seguramente usados por el primer circulo FFF (Family Friends Fools), quizá atrofia la capacidad de argumentar en contra, y para el creador de resolver la frustración, es en estas argumentaciones y debates donde se podría ver el cobre de los planteamientos del proyecto, que quizá a la larga sean los que convenza a alguien de ir a su concierto.
- Exponer la imagen hasta el cansancio es algo que puede favorecer a una celebridad pero no es compatible con muchos proyectos musicales.
